Transport_Web/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^transport/', include('transport.urls', namespace="transport")),
    url(r'^admin/', include(admin.site.urls)),
]

transport/urls.py
from django.conf.urls import url

from transport import views

urlpatterns = [
    url(r'^area_statistics', views.area_statistics, name='area_statistics'),
    url(r'^region', views.region, name='region'),
    url(r'^echarts', views.echarts, name='echarts'),
    url(r'^label_the_road', views.label_the_road, name='label_the_road'),
    url(r'^showpath', views.showpath, name='showpath'),
    url(r'^heatmap', views.heatmap, name='heatmap'),
    url(r'^violation_statistics', views.violation_statistics, name='heaviolation_statisticstmap'),

    url(r'^$', views.index, name='index'),
]

transport/models.py
from django.db import models

# Create your models here.

transport/views.py
# coding: utf-8
from django.shortcuts import render,render_to_response
from django.http import HttpResponse,HttpResponseRedirect
from django.template import RequestContext
from django.core.urlresolvers import reverse
from Transport_Web.helpers import *
from Transport_Web.settings import STATIC_ROOT
from django.views.decorators.http import require_GET, require_POST
from transport.direction import *
from os.path import normpath,join
import pytz,copy,csv,time
from transport.json_handler import generate_option,generate_delay_option,generate_multi_option,generate_model_option,generate_violation_option
from operator import itemgetter, attrgetter
from transport.predict import predict
pinyin_hash = {"dongcheng" : 1, "xicheng" : 2, "chaoyang":5, "haidian":6, "fengtai":7, "shijingshan":8, "daxing":18}

IN_RECTANGLE_AREA = 0
IN_POLYGON_AREA = 1
# Create your views here.


def index(request):
    roads_set,roads_directions=get_all_paths()
    polyline_js_code=poly_line_js(roads_set,roads_directions)
    clockwise=direction(1,u"顺时针")
    anti_clockwise=direction(-1,u"逆时针")
    directions=[clockwise,anti_clockwise]
    noise_invisible=1
    return render(request, 'transport/baidu.html',locals())
def region(request):
    slat=float(request.GET.get("slat"))
    slng=float(request.GET.get("slng"))
    elat=float(request.GET.get("elat"))
    elng=float(request.GET.get("elng"))
    #print(u"左上经纬度：" + str(slng) + u"," + str(slat) + u", 右下经纬度:" + str(elng) + u"," + str(elat))

    table_arr=load_pickle_from(STATIC_ROOT+os.sep+"WFJBXX_ORG.pkl")
    table_1=table_arr[0]
    data_points=get_points_in_region(table_1,slat,slng,elat,elng)
    return success_response(str(len(data_points)))
def get_date_list_and_data(input_file_path,region_name,type):
    csvfile = open(input_file_path,"rb")
    reader = csv.reader(csvfile)
    data_dict = {}
    data_dict["name"]=region_name
    data_dict["type"] = type
    date_list = []
    data_list = []
    for i,row in enumerate(reader):
        date_time = row[0]
        date_time_splt = date_time.split(" ")
        date_time_tmp = date_time_splt[0]+"\n"+date_time_splt[1]
        date_list.append(date_time_tmp)
        violation_cnt = float(row[1])
        data_list.append(violation_cnt)
    data_dict["data"]= data_list
    return date_list,[data_dict]
def violation_statistics(request):
    region_name = request.GET.get('region_name', "chaoyang")
    month = int(request.GET.get('month', 0))
    week_aggregate = int(request.GET.get('week_aggregate', 0))

    dir_name = "processed_monthdata"
    if week_aggregate:
        dir_name = "week_processed_monthdata"

    input_file_path = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))+os.sep+"data" + os.sep +dir_name + os.sep + str(month)+ os.sep +region_name+".csv"
    type = "bar"
    date_list,vio_data = get_date_list_and_data(input_file_path,region_name,type)

    json_file_name='violation_option_tmp.json'
    generate_violation_option(json_file_name,type,week_aggregate,region_name,date_list,vio_data)
    addr = '/static/option/'+json_file_name
    return success_response(addr)

def area_statistics(request):
    data_type = int(request.GET.get('data_type', -1))  #表示的是采用哪种json输出数据格式显示
    point_type = int(request.GET.get('point_type', 1))  #0:全部，1:应急车道，2，3，4...
    type = request.GET.get('region_type','')
    point_list_tmp=request.POST.get('point_list','')
    point_list = json.loads(point_list_tmp)

    #单独的区域进行分析
    if(type == "single"):
        min_time_size,is_corr = 1,0
        points_info_dict = single_area_statistic(point_list, point_type, data_type, min_time_size, is_corr)
        data_points_json = json.dumps(points_info_dict, sort_keys=True, indent=4)
        print(data_points_json)
        json_file_name = 'option_model_tmp.json'
        generate_option(point_type,json_file_name,"line", **points_info_dict)


        '''data_file_path=normpath(join(BASE_DIR,'static','option')) + os.sep + "data.json"
        data_file=open(data_file_path,"r")
        json_str=data_file.read()
        data_file.close()
        json_dict=json.loads(json_str)'''
        #json_dict = json.loads(data_points_json)

        #如果看拥堵,第一个改成1,如果看举报,第一个参数改成0
        #generate_model_option(0,json_file_name,"line", **json_dict)

        #print(data_points_json)
        addr = '/static/option/'+json_file_name
        return success_response(addr)
    elif(type=="multi"): #两个区域进行分析

        area_points_list = point_list
        min_time_size,is_corr = 1,1
        # current use for machine learning
        multi_area_statistic(area_points_list, point_type, data_type, min_time_size, is_corr)

        #preview multi-area correlation
        '''corr_dict = multi_area_statistic(area_points_list, point_type, data_type, min_time_size, is_corr)


        #data_points_json = json.dumps(points_info_list, indent=4)
        #print(data_points_json)
        json_file_name='option_multi_tmp.json'
        generate_multi_option(point_type,json_file_name,"line", **corr_dict)
        addr = '/static/option/'+json_file_name
        return success_response(addr)'''
        return
    elif(type=='delay'):
        delay_time = float(request.GET.get('del_time', -1))
        delay_cnt = int(request.GET.get('del_cnt', -1))
        min_time_size, is_corr = delay_time, 1
        corr_dict = delay_area_statistic(point_list, point_type, data_type, delay_cnt, min_time_size, is_corr)
        json_file_name='option_delay_tmp.json'
        generate_delay_option(point_type,json_file_name,"line", **corr_dict)
        addr = '/static/option/'+json_file_name
        return success_response(addr)



def make_length_equal(datatime_list1, date_list1, pos_list1, neg_list1, datatime_list2, date_list2, pos_list2, neg_list2):
    if (datatime_list1[0] < datatime_list2[0]):
        index = 0
        while (index < len(datatime_list1) and datatime_list1[index] != datatime_list2[0]):
            index += 1
        for j in range(index):
            datatime_list2.insert(j, datatime_list1[j])
            date_list2.insert(j, datatime_list1[j])
            pos_list2.insert(j, 0)
            neg_list2.insert(j, 0)
    else:
        index = 0
        while (index < len(datatime_list2) and datatime_list2[index] != datatime_list1[0]):
            index += 1
        for j in range(index):
            datatime_list1.insert(j, datatime_list2[j])
            date_list1.insert(j, datatime_list2[j])
            pos_list1.insert(j, 0)
            neg_list1.insert(j, 0)
    if (datatime_list1[len(datatime_list1) - 1] < datatime_list2[len(datatime_list2) - 1]):
        index = len(datatime_list2) - 1
        while (index >= 0 and datatime_list2[index] != datatime_list1[len(datatime_list1) - 1]):
            index -= 1
        for j in range(index + 1, len(datatime_list2)):
            datatime_list1.insert(j, datatime_list2[j])
            date_list1.insert(j, datatime_list2[j])
            pos_list1.append(0)
            neg_list1.append(0)
    else:
        index = len(datatime_list1) - 1
        while (index >= 0 and datatime_list1[index] != datatime_list2[len(datatime_list2) - 1]):
            index -= 1
        for j in range(index + 1, len(datatime_list1)):
            datatime_list2.insert(j, datatime_list1[j])
            date_list2.insert(j, datatime_list1[j])
            pos_list2.append(0)
            neg_list2.append(0)
    return [pos_list1,pos_list2,neg_list1,neg_list2]

#将两个序列的长度变成相同的
def get_equal_length_lists(points_info_first, points_info_second, type):
    date_list1 = points_info_first['date_list']
    datatime_list1 = points_info_first['type' + str(type)]['datatime']
    pos_list1 = points_info_first['type' + str(type)]['posNum']
    neg_list1 = points_info_first['type' + str(type)]['negNum']
    date_list2 = points_info_second['date_list']
    datatime_list2 = points_info_second['type' + str(type)]['datatime']
    pos_list2 = points_info_second['type' + str(type)]['posNum']
    neg_list2 = points_info_second['type' + str(type)]['negNum']
    #注意在使两个序列等长时，要优先比较每种type的datetime_list，而不能比较date_list，因为是引用，所以会修改date_list使其成为等长，因而后续计算始终date_list相等,而type中的却不一定等长，使得函数失效
    return make_length_equal(datatime_list1, date_list1, pos_list1, neg_list1, datatime_list2, date_list2, pos_list2, neg_list2)

#计算相关性的值
def calc_corr(pos_list1,pos_list2,neg_list1,neg_list2):
    pos_list1_avg, neg_list1_avg, pos_list2_avg, neg_list2_avg = 0.0, 0.0, 0.0, 0.0
    for j in range(len(pos_list1)):
        pos_list1_avg += pos_list1[j]
        pos_list2_avg += pos_list2[j]
        neg_list1_avg += neg_list1[j]
        neg_list2_avg += neg_list2[j]
    pos_list1_avg /= len(pos_list1)
    pos_list2_avg /= len(pos_list1)
    neg_list1_avg /= len(pos_list1)
    neg_list2_avg /= len(pos_list1)
    sum_pos_xy, sum_neg_xy, sum_pos_x2, sum_pos_y2, sum_neg_x2, sum_neg_y2 = 0, 0, 0, 0, 0, 0
    for j in range(len(pos_list1)):
        sum_pos_xy += (pos_list1[j] - pos_list1_avg) * (pos_list2[j] - pos_list2_avg)
        sum_pos_x2 += pow(pos_list1[j] - pos_list1_avg, 2)
        sum_pos_y2 += pow(pos_list2[j] - pos_list2_avg, 2)
        sum_neg_xy += (neg_list1[j] - neg_list1_avg) * (neg_list2[j] - neg_list2_avg)
        sum_neg_x2 += pow(neg_list1[j] - neg_list1_avg, 2)
        sum_neg_y2 += pow(neg_list2[j] - neg_list2_avg, 2)
    print(str(sum_pos_xy) + ' ' + str(sum_pos_x2) + ' ' + str(sum_pos_y2))
    print(str(sum_neg_xy) + ' ' + str(sum_neg_x2) + ' ' + str(sum_neg_y2))
    print('------------------------------------')
    if(abs(math.sqrt(sum_pos_x2 * sum_pos_y2))<EPS):
        r_pos_xy = 0.0
    else:
        r_pos_xy = sum_pos_xy / math.sqrt(sum_pos_x2 * sum_pos_y2)
    if (abs(math.sqrt(sum_neg_x2 * sum_neg_y2)) < EPS):
        r_neg_xy = 0.0
    else:
        r_neg_xy = sum_neg_xy / math.sqrt(sum_neg_x2 * sum_neg_y2)
    return [r_pos_xy, r_neg_xy]

#返回table_arr的list和对应的type_list
def get_table_from_type(point_type):
    table_arr = load_pickle_from(STATIC_ROOT + os.sep + 'labeledpoints.pkl')
    tmp_table_arr = []

templates/transport/diffcolor3.html
{% extends "transport/diff_color_base3.html" %}
{% load static from staticfiles %}
{% block title %}点标注结果{% endblock %}
{% block headscript %}

{% endblock %}
{% block endscript %}
<script type="text/javascript">
     var myModal=$("#modal_body");
     var echart_body=$("#echart_body");
     echart_body.hide();
     var modal_dialog=$("#modal_dialog");
     var myChart = echarts.init(document.getElementById('echart_body'));
     var modal_inner=$("#modal_inner");
</script>
<script type="text/javascript">
    function handle_result_from_json(result)
    {
        var addr=result.message;
        if(typeof addr == "object"){
            var corr_list = addr.corr;
            var str_corr = "";
            for(var i=0;i<corr_list.length;i++){
                str_corr += ("i="+i+"  pos_corr="+corr_list[i][0]+"  neg_corr="+corr_list[i][1]+"\n");
            }
            alert(str_corr);
            addr = addr.addr;
        }
        else {
            $.get(addr).done(function (rtn_json) {
            myModal.css("height", "800px");
            myModal.css("weight", "1200px");
            modal_dialog.css("height", "800px");
            modal_dialog.css("weight", "1200px");
            echart_body.css("height", "800px");
            echart_body.css("weight", "1200px");
            modal_inner.hide();
            echart_body.show();
            //JSON.parse(rtn_json);
            myChart.setOption(rtn_json);
            myModal.modal('show');
        });
        }
    }
</script>
{% endblock %}

templates/transport/transport_base.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=EmulateIE9" />
    <title>{% block title %}{% endblock %}</title>
    <style type="text/css">
        html,body{
            margin:0;
            width:100%;
            height:100%;
            background:#ffffff;
        }
        #map{
            width:100%;
            height:95%;
        }
        #modal_dialog,#modal_body{
            width:1200px;
            height:1300px;
        }


        #navi{
            width:100%;
            height:5%;
        }
        #panel {
            position: absolute;
            top:30px;
            left:10px;
            z-index: 999;
            color: #fff;
        }
        #login{
            position:absolute;
            width:300px;
            height:40px;
            left:50%;
            top:50%;
            margin:-40px 0 0 -150px;
        }
        #login input[type=password]{
            width:200px;
            height:30px;
            padding:3px;
            line-height:30px;
            border:1px solid #000;
        }
        #login input[type=submit]{
            width:80px;
            height:38px;
            display:inline-block;
            line-height:38px;
        }
    </style>
    <!-- 写点样式，让轮播好看点 -->
    <style>
    ul, ol { padding: 0;}
    .banner { position: relative; overflow: auto; text-align: center;}
    .banner li { list-style: none; }
    .banner ul li { float: left; }
    #b04 { width: 640px;}
    #b04 .dots { position: absolute; left: 0; right: 0; bottom: 20px;}
    #b04 .dots li
    {
        display: inline-block;
        width: 10px;
        height: 10px;
        margin: 0 4px;
        text-indent: -999em;
        border: 2px solid #fff;
        border-radius: 6px;
        cursor: pointer;
        opacity: .4;
        -webkit-transition: background .5s, opacity .5s;
        -moz-transition: background .5s, opacity .5s;
        transition: background .5s, opacity .5s;
    }
    #b04 .dots li.active
    {
        background: #fff;
        opacity: 1;
    }
    #b04 .arrow { position: absolute; top: 200px;}
    #b04 #al { left: 15px;}
    #b04 #ar { right: 15px;}

    label.legend{display:inline-block;font-weight: normal;margin-right: 5px;font-size: 12px;cursor: pointer;}
    label.legend.disabled{color: #d3d3d3 !important;}
    label.legend.disabled .label{background-color: #d3d3d3 !important;}
    label.legend .label{width: 12px;height: 8px;margin-right: 5px;vertical-align: middle;margin-bottom: 2px;}
    label.legend .label:empty{display: inline-block;}
    </style>
    <script type="text/javascript" src="http://api.map.baidu.com/api?v=2.0&ak=eM0GfCwd27kZRyM49ZOkvkOaidDXz6Wf"></script>
    <link rel="stylesheet" href="{% static "css/DrawingManager_min.css" %}" />
    <script type="text/javascript" src="{% static "js/jquery-1.11.3.min.js" %}"></script>
    <link rel="stylesheet" type="text/css" media="screen" href="{% static "css/bootstrap.min.css" %}" />
    <script type="text/javascript" src="{% static "js/bootstrap.min.js" %}" charset="UTF-8"></script>
    <link rel="stylesheet" type="text/css" media="screen" href="{% static "css/font-awesome.css" %}" />
    <link rel="stylesheet" href="{% static "css/awesome-bootstrap-checkbox.css" %}" />
    <link rel="stylesheet" type="text/css" media="screen" href="{% static "css/jquery-confirm.min.css" %}" />
    <script type="text/javascript" src="{% static "js/jquery-confirm.min.js" %}" charset="UTF-8"></script>
    <script type="text/javascript" src="{% static "js/DrawingManager_min.js" %}"></script>
    <script type="text/javascript" src="{% static "js/DrawingManager_min.js" %}"></script>
    <script>

    function show_banner()
    {
        var unslider04 = $('#b04').unslider({
            speed:500,
            delay:3000,
            dots: true
        }),
        data04 = unslider04.data('unslider');

        $('.unslider-arrow04').click(function() {
            var fn = this.className.split(' ')[1];
            data04[fn]();
        });
    }
    function distance(x,y){
        lat_sqr=Math.pow((x.lat- y.lat),2);
        lng_sqr=Math.pow((x.lng- y.lng),2);
        return Math.sqrt(lat_sqr+lng_sqr);
    }
    var currDivIndex=100;
    function set_z_index_of(obj)
    {
        currDivIndex++;
        //鼠标进入z-index增加10
        obj.css("z-index", ""+(currDivIndex) );
    }
    </script>
    {% block head %}{% endblock %}
</head>

<body>
    {% block navigator %}
        <nav class="navbar navbar-default" style="margin-bottom:0" id ="navi">
          <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="{% url 'transport:index' %}">北京交通可视化系统</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">
                <li ><a href="{% url 'transport:index' %}">道路标注</a></li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">点标注结果 <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><a href="{% url 'transport:showpath' %}">所有点</a></li>
                    <li><a href="{% url 'transport:showpath' %}?noise_invisible=1&data_type=0">所有点(仅标注点)</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="{% url 'transport:showpath' %}?noise_invisible=1&data_type=1">应急车道点标注</a></li>
                    <li><a href="{% url 'transport:showpath' %}?noise_invisible=1&data_type=2">违反指示标线点标注</a></li>
                    <li><a href="{% url 'transport:showpath' %}?noise_invisible=1&data_type=3">非机动车道点标注</a></li>
                    <li><a href="{% url 'transport:showpath' %}?noise_invisible=1&data_type=4">公交车道点标注</a></li>
                  </ul>
                </li>
                  <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">点标注（顺逆时针分开）<span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><a href="{% url 'transport:showpath' %}">所有点</a></li>
                    <li><a href="{% url 'transport:showpath' %}?noise_invisible=1&data_type=0&split_show=1">所有点(仅标注点)</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="{% url 'transport:showpath' %}?noise_invisible=1&data_type=1&split_show=1">应急车道点标注</a></li>
                    <li><a href="{% url 'transport:showpath' %}?noise_invisible=1&data_type=2&split_show=1">违反指示标线点标注</a></li>
                    <li><a href="{% url 'transport:showpath' %}?noise_invisible=1&data_type=3&split_show=1">非机动车道点标注</a></li>
                    <li><a href="{% url 'transport:showpath' %}?noise_invisible=1&data_type=4&split_show=1">公交车道点标注</a></li>
                  </ul>
                </li>
              </ul>
            </div><!-- /.navbar-collapse -->
          </div><!-- /.container-fluid -->
        </nav>
    {% endblock %}
    {% block content %}
    {% endblock %}
</body>
</html>

templates/transport/transport_base3.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=EmulateIE9" />
    <title>{% block title %}{% endblock %}</title>
    <style type="text/css">
        html,body{
            margin:0;
            width:100%;
            height:100%;
            background:#ffffff;
        }
        #map{
            width:100%;
            height:95%;
        }
        #modal_dialog{
            width:1000px;
            height:600px;
        }


        #navi{
            width:100%;
            height:5%;
        }
        #panel {
            position: absolute;
            top:30px;
            left:10px;
            z-index: 999;
            color: #fff;
        }
        #login{
            position:absolute;
            width:300px;
            height:40px;
            left:50%;
            top:50%;
            margin:-40px 0 0 -150px;
        }
        #login input[type=password]{
            width:200px;
            height:30px;
            padding:3px;
            line-height:30px;
            border:1px solid #000;
        }
        #login input[type=submit]{
            width:80px;
            height:38px;
            display:inline-block;
            line-height:38px;
        }
    </style>
    <!-- 写点样式，让轮播好看点 -->
    <style>
    ul, ol { padding: 0;}
    .banner { position: relative; overflow: auto; text-align: center;}
    .banner li { list-style: none; }
    .banner ul li { float: left; }
    #b04 { width: 640px;}
    #b04 .dots { position: absolute; left: 0; right: 0; bottom: 20px;}
    #b04 .dots li
    {
        display: inline-block;
        width: 10px;
        height: 10px;
        margin: 0 4px;
        text-indent: -999em;
        border: 2px solid #fff;
        border-radius: 6px;
        cursor: pointer;
        opacity: .4;
        -webkit-transition: background .5s, opacity .5s;
        -moz-transition: background .5s, opacity .5s;
        transition: background .5s, opacity .5s;
    }
    #b04 .dots li.active
    {
        background: #fff;
        opacity: 1;
    }
    #b04 .arrow { position: absolute; top: 200px;}
    #b04 #al { left: 15px;}
    #b04 #ar { right: 15px;}

    label.legend{display:inline-block;font-weight: normal;margin-right: 5px;font-size: 12px;cursor: pointer;}
    label.legend.disabled{color: #d3d3d3 !important;}
    label.legend.disabled .label{background-color: #d3d3d3 !important;}
    label.legend .label{width: 12px;height: 8px;margin-right: 5px;vertical-align: middle;margin-bottom: 2px;}
    label.legend .label:empty{display: inline-block;}
    </style>
    <script type="text/javascript" src="http://api.map.baidu.com/api?v=2.0&ak=eM0GfCwd27kZRyM49ZOkvkOaidDXz6Wf"></script>
    <link rel="stylesheet" href="{% static "css/DrawingManager_min.css" %}" />
    <script type="text/javascript" src="{% static "js/jquery-1.11.3.min.js" %}"></script>
    <link rel="stylesheet" type="text/css" media="screen" href="{% static "css/bootstrap.min.css" %}" />
    <script type="text/javascript" src="{% static "js/bootstrap.min.js" %}" charset="UTF-8"></script>
    <link rel="stylesheet" type="text/css" media="screen" href="{% static "css/font-awesome.css" %}" />
    <link rel="stylesheet" href="{% static "css/awesome-bootstrap-checkbox.css" %}" />
    <link rel="stylesheet" type="text/css" media="screen" href="{% static "css/jquery-confirm.min.css" %}" />
    <script type="text/javascript" src="{% static "js/jquery-confirm.min.js" %}" charset="UTF-8"></script>
    <script type="text/javascript" src="{% static "js/DrawingManager_min.js" %}"></script>
    <script type="text/javascript" src="{% static "js/DrawingManager_min.js" %}"></script>
    <script>

    function show_banner()
    {
        var unslider04 = $('#b04').unslider({
            speed:500,
            delay:3000,
            dots: true
        }),
        data04 = unslider04.data('unslider');

        $('.unslider-arrow04').click(function() {
            var fn = this.className.split(' ')[1];
            data04[fn]();
        });
    }
    function distance(x,y){
        lat_sqr=Math.pow((x.lat- y.lat),2);
        lng_sqr=Math.pow((x.lng- y.lng),2);
        return Math.sqrt(lat_sqr+lng_sqr);
    }
    var currDivIndex=100;
    function set_z_index_of(obj)
    {
        currDivIndex++;
        //鼠标进入z-index增加10
        obj.css("z-index", ""+(currDivIndex) );
    }
    </script>
    {% block head %}{% endblock %}
</head>

<body>
    {% block navigator %}
        <nav class="navbar navbar-default" style="margin-bottom:0" id ="navi">
          <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="{% url 'transport:index' %}">北京交通可视化系统</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">
                <li ><a href="{% url 'transport:index' %}">道路标注</a></li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">点标注结果 <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><a href="{% url 'transport:showpath' %}?noise_invisible=0&data_type=0">所有点</a></li>
                    <li><a href="{% url 'transport:showpath' %}?noise_invisible=1&data_type=0">所有点(仅标注点)</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="{% url 'transport:showpath' %}?noise_invisible=1&data_type=1">应急车道点标注</a></li>
                    <li><a href="{% url 'transport:showpath' %}?noise_invisible=1&data_type=2">违反指示标线点标注</a></li>
                    <li><a href="{% url 'transport:showpath' %}?noise_invisible=1&data_type=3">非机动车道点标注</a></li>
                    <li><a href="{% url 'transport:showpath' %}?noise_invisible=1&data_type=4">公交车道点标注</a></li>
                  </ul>
                </li>
              </ul>
            </div><!-- /.navbar-collapse -->
          </div><!-- /.container-fluid -->
        </nav>
    {% endblock %}
    {% block content %}
    {% endblock %}
</body>
</html>